### ISSUE TITLE
support `crop()` for `rowGeometries`

### ISSUE THREAD

**Issue by alikhuseynov** [pachterlab/SpatialFeatureExperiment#15]
it would be useful to support the `crop` or SFE for transcript spots or whatever is stored in `rowGeometires`, to add arg `rowGeometryName` or similar

**Comment by lambdamoses** [comment]
Yes, these are the implications when we read transcript spots, and a reason why the z-planes are split into separate XY geometries by default. Cropping XYZ geometries would be more complicated. Not sure if I can address all implications of using rowGeometries by next Monday; I will probably gradually add these features as "bug fixes" after the 3.18 release.

**Comment by alikhuseynov** [comment]
ok, thanks. I can help where is needed.

**Comment by lambdamoses** [comment]
Done in https://github.com/pachterlab/SpatialFeatureExperiment/commit/efed2e7c15a7949b9614c66a963d8e30a88d3f2c
