### ISSUE TITLE
codex data

### ISSUE THREAD

**Issue by Elena983** [pachterlab/SpatialFeatureExperiment#16]
Hi
I would like to create the CODEX sfe.
How to create it.
What parameters do I need for this?
I have
CellID,
X,Y centroids
Cell_type

If need be I also have in my countmatrix
Area	
MajorAxisLength	
MinorAxisLength	
Eccentricity	
Solidity	
Extent	
Orientation

**Comment by lambdamoses** [comment]
See vignette and documentation on creating SFE objects: https://pachterlab.github.io/voyager/articles/create_sfe.html#create-sfe-object-from-scratch Right now there isn't a function to directly read CODEX output, so the SFE object needs to be created from scratch. Basically, suppose you have a data frame called `df` for the cell coordinates and metadata with columns CellID, X, Y, Cell_type, Area, MajorAxisLength, MinorAxisLength, Eccentricity, Solidity, Extent, and Orientation, and matrix `mat` with rows for genes and columns for cells, you can do this to construct the SFE object:

```
sfe <- SpatialFeatureExperiment(list(counts = mat), colData = df, spatialCoordsNames = c("X", "Y"))
```

The `spatialCoordsNames` argument is used to take the X and Y columns in `df` as the centroid coordinates. OK, I think I should put the vignette on creating SFE objects in a more visible place on the Voyager documentation website.

**Comment by Elena983** [comment]
Thank you for replying.
I received the error. 
```
Error in `spatialCoords<-`(`*tmp*`, value = as.matrix(colData(spe)[i])) : 
  is.numeric(value) is not TRUE
```

Could you please have a look at my data?
[metadata.csv](https://github.com/pachterlab/SpatialFeatureExperiment/files/13204652/metadata.csv)
[gene_by_cell.csv](https://github.com/pachterlab/SpatialFeatureExperiment/files/13204653/gene_by_cell.csv)

df <- read.csv2('metadata.csv', head = TRUE, sep=",")
matrix <- as.matrix(read.csv2('gene_by_cell.csv', head = TRUE, sep=","))
mat <- t(matrix)
sfe <- SpatialFeatureExperiment(list(counts = mat), 
                                colData = df, 
                                spatialCoordsNames = c("X", "Y"))

**Comment by Elena983** [comment]
Thank you
I am done with it. 
Beautiful result
