### ISSUE TITLE
Use geometries or bounding boxes to split up SFE object

### ISSUE THREAD

**Issue by lambdamoses** [pachterlab/SpatialFeatureExperiment#28]
This is useful say when multiple pieces of tissue from different subjects are mounted in the same Visium capture area because each piece is pretty small. In this case, it would be cool to use bounding boxes or geometries to split the different pieces into different SFE objects since it would make sense to compute the spatial metrics separately on each piece so the results can be compared. 

It's annoying to have to figure out the bounding box coordinates by plotting the image while labeling the plot axes. When tissue boundaries are available, we can split the Visium spots into tissues based on intersection with different pieces of tissue and each piece of at least a certain size will become a separate sample. Burning question: what if one Visium spot intersects two nearby pieces at once? Maybe we can require the different pieces to be at least a certain distance apart, or that we crop off the part of that offending Visium spot that doesn't overlap with this piece of tissue. What to do with gene expression? Since the transcripts can diffuse between nearby spots, maybe it's not too bad to say they're uniformly distributed within the spot, but something like `BayesSpace` can be used to computationally increase the resolution to get more plausible splitting.

**Comment by lambdamoses** [comment]
Related, changing sample_id without splitting the SFE object: https://github.com/pachterlab/SpatialFeatureExperiment/issues/31

**Comment by lambdamoses** [comment]
Yes, `st_intersects` is the right way, though I haven't benchmarked whether the other geometry predicate functions may be faster or if `st_intersects(centroids, polygon)` or `st_intersects(polygon, centroids)`is faster when there are many centroids and few polygons. `st_intersects` is way faster than `st_intersection`, and the latter is used in plotting functions in Voyager to zoom into a smaller bounding box and it doesn't take more than a few seconds to crop out a few thousand cells from hundreds of thousands. But I haven't benchmarked `st_intersects` on hundreds of thousands of cells. How many cells do you have, and how many polygons in your `geom`?

**Comment by sgunz** [comment]
Thank you for your response! You are right, `st_intersects` is quite fast and should do the job. My problem was that I subsetted each individual polygon sequentially while doing it with all geometries at once takes roughly the same amount of time to calculate.  My dataset has around 360'000 cells and 51 polygons.

I did a little `microbenchmark`, the results are given in seconds. The commands with `annotGeometry(sfe, "GC")[50, ]` refers to my initial approach in which I subsetted sequentially. `st_intersects(polygon, centroids)` slightly outperforms `st_intersects(centroids, polygon)`.
 
![image](https://github.com/pachterlab/SpatialFeatureExperiment/assets/24435148/e2b44b72-8dff-46ec-8ea1-14aa3a3fd380)

|expr                                                                               |      min|       lq|     mean|   median|       uq|      max| neval|
|:----------------------------------------------------------------------------------|--------:|--------:|--------:|--------:|--------:|--------:|-----:|
|st_intersects(centroids(sfe), annotGeometry(sfe, "GC"), sparse = FALSE)            | 1.568921| 1.622178| 1.667294| 1.642456| 1.672134| 2.455978|   100|
|st_intersects(annotGeometry(sfe, "GC"), centroids(sfe), sparse = FALSE)            | 1.155784| 1.189365| 1.209071| 1.203450| 1.225450| 1.363769|   100|
|st_intersects(centroids(sfe), annotGeometry(sfe, "GC")[50, ],      sparse = FALSE) | 1.350748| 1.385482| 1.439528| 1.405980| 1.425414| 2.206677|   100|
|st_intersects(annotGeometry(sfe, "GC")[50, ], centroids(sfe),      sparse = FALSE) | 1.042136| 1.069069| 1.094642| 1.089006| 1.107050| 1.261549|   100|
