### ISSUE TITLE
Problem Subsetting SpatialFeatureExperiment Object on Bioconductor 3.20

### ISSUE THREAD

**Issue by aasingh2** [pachterlab/SpatialFeatureExperiment#58]
Hi,
I am back again with a issue :). I recently updated to the latest version of Bioconductor (3.20) and have encountered issues when trying to subset a SpatialFeatureExperiment (SFE) object. The SFE object, which I've been using for weeks without issues, works perfectly for my colleagues who are still on older versions of Bioconductor. However, subsetting columns now fails for me with the following commands:

1. Subsetting by column name or column index
`sfe[, 1]`
Error in subset.listw(graphs_sub[[s]][[m]][[g]], j_sample) : 
  Not yet able to subset general weights lists
traceback()
5: stop("Not yet able to subset general weights lists")
4: subset.listw(graphs_sub[[s]][[m]][[g]], j_sample)
3: subset(graphs_sub[[s]][[m]][[g]], j_sample)
2: sfe[, 1]
1: sfe[, 1]

2. Subsetting by  column condition
`sfe[, colData(sfe)$coarse_cell_type == "T cell"]`
Error in subset.listw(graphs_sub[[s]][[m]][[g]], j_sample) : 
  Not yet able to subset general weights lists
traceback()
5: stop("Not yet able to subset general weights lists")
4: subset.listw(graphs_sub[[s]][[m]][[g]], j_sample)
3: subset(graphs_sub[[s]][[m]][[g]], j_sample)
2: sfe[, colData(sfe)$coarse_cell_type == "T cell"]
1: sfe[, colData(sfe)$coarse_cell_type == "T cell"]

Subsetting rows works without any issues. Is this a known problem with the new Bioconductor version? Since subsetting works fine with the SFEdata package, I’m wondering if this issue is specific to XOA v3. For the time being, I have downgraded to Bioconductor version 3.19 to continue working with the object. However, it would be great to have this issue resolved in the current Bioconductor version of the package.

Thank you!

**Comment by alikhuseynov** [comment]
Hi, that seems to be only related when subsetting graphs, else it works fine. Try to use recent Bioc 3.20 and recent updates from `devel` branch, maybe it will fix that.

**Comment by lambdamoses** [comment]
I think this is caused by a recent update calling `subset.listw` instead of reconstructing the graphs. What method was used to construct the graph? Did you use distance-based edge weights?

**Comment by lambdamoses** [comment]
I found the culprit: https://github.com/r-spatial/spdep/blob/dbd3074b8822ec669fea628061bce88fe77c5bf2/R/subset.nb.R#L61-L62 I'll fix it to day or tomorrow

**Comment by lambdamoses** [comment]
@aasingh2 The changes have been pushed to devel. See if you get more issues.

**Comment by lambdamoses** [comment]
In the new version, the graphs are subsetted rather than reconstructed when you subset the SFE object. I just found out that in some cases this can drastically affect spatial analysis results. I don't know theoretically which analyses are more sensitive to what kind of changes to the spatial neighborhood graph. I can't say whether it's "correct" to subset or reconstruct. So I think I'll introduce an option to allow you to choose whether to subset or reconstruct. Does this sound reasonable? What do you think?

**Comment by alikhuseynov** [comment]
> In the new version, the graphs are subsetted rather than reconstructed when you subset the SFE object. I just found out that in some cases this can drastically affect spatial analysis results, say when the k nearest neighbor graph is subsetted, cells on the edge of the region can lose some of their original neighbors. I don't know theoretically which analyses are more sensitive to what kind of changes to the spatial neighborhood graph. I can't say whether it's "correct" to subset or reconstruct. So I think I'll introduce an option to allow you to choose whether to subset or reconstruct. Does this sound reasonable? What do you think?

Sounds very responsible! I tend to think that reconstructing graphs after subset is more correct. But an option would be quite handy. Thanks

**Comment by lambdamoses** [comment]
@aasingh2 I introduced an option `SFE_graph_subset` to choose whether to subset the graphs or reconstruct like in older versions of SFE. To subset, set `options(SFE_graph_subset = TRUE)`, which is the default. To reconstruct, set `options(SFE_graph_subset = FALSE)`. If it works fine for you then I'll merge this into the `main` branch.

**Comment by lambdamoses** [comment]
I wasn't thinking about the case when only 1 cell is left, in which case the graph doesn't make sense anyway.

**Comment by lambdamoses** [comment]
@aasingh2 I pushed an update that drops the graph when there's only 1 cell left because the graph doesn't make sense. I have no idea what causes the error `length of Dimnames[[2]] (77654) is not equal to Dim[2] (12796)` though. Can you share your code used to make the graph?

**Comment by aasingh2** [comment]
@lambdamoses  I tested everything again after clearing my environments with the devel version of the package (SpatialFeatureExperiment_1.9.4). Both options, options(SFE_graph_subset = FALSE) and options(SFE_graph_subset = TRUE), are now working perfectly fine, and everything is functioning as expected.
Thanks for the fix!

**Comment by lambdamoses** [comment]
Merged to main and pushed to Bioconductor
